[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nafhtr"
version = "0.1.0"
description = "An HTR pipeline for historical text recognition. The text lines are detected using RF-DETR model and the text is detected using a vision encoder-decoder model."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "langdetect>=1.0.9",
    "lxml>=6.0.2",
    "marimo>=0.17.6",
    "numpy>=1.24.3",
    "opencv-python-headless>=4.8.1.78",
    "pillow>=9.5.0",
    "pydantic>=2.6.1",
    "rfdetr>=1.6.4",
    "shapely>=2.0.6",
    "torch>=2.4.0",
    "transformers>=5.1.0",
    "yattag>=1.16.1",
    "supervision>=0.27.0",
    "huggingface-hub>=1.19.0",
]
authors = [
  {name = "Mikko Lipsanen", email = "mikko.lipsanen@kansallisarkisto.fi"},
  {name = "Atte Föhr", email = "atte.fohr@kansallisarkisto.fi"},
  {name = "John Mäkelä", email = "john.makela@kansallisarkisto.fi"},
]
maintainers = [
  {name = "Mikko Lipsanen", email = "mikko.lipsanen@kansallisarkisto.fi"},
  {name = "Atte Föhr", email = "atte.fohr@kansallisarkisto.fi"},
  {name = "John Mäkelä", email = "john.makela@kansallisarkisto.fi"}
]
license = "Apache-2.0"
license-files = ["LICEN[CS]E.*"]
keywords = ["document understanding", "handwriting recognition", "ocr", "htr"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]

[project.urls]
Homepage = "https://github.com/Kansallisarkisto-AI/rfdetr_trocr_pipeline"
Documentation = "https://github.com/Kansallisarkisto-AI/rfdetr_trocr_pipeline"
Repository = "https://github.com/Kansallisarkisto-AI/rfdetr_trocr_pipeline"
"Bug Tracker" = "https://github.com/Kansallisarkisto-AI/rfdetr_trocr_pipeline/issues"
